# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/manuals', type: :request do
  # Manual. As you add validations to Manual, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {marca: :Brastemp, codigo: :abc, modelo: :plus, path: 'www.marca.com'}
  end

  let(:invalid_attributes) do
    {created_at: null}
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Manual.create! valid_attributes
      get manuals_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      manual = Manual.create! valid_attributes
      get manual_url(manual)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_manual_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      manual = Manual.create! valid_attributes
      get edit_manual_url(manual)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Manual' do
        expect do
          post manuals_url, params: { manual: valid_attributes }
        end.to change(Manual, :count).by(1)
      end

      it 'redirects to the created manual' do
        post manuals_url, params: { manual: valid_attributes }
        expect(response).to redirect_to(manual_url(Manual.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Manual' do
        expect do
          post manuals_url, params: { manual: invalid_attributes }
        end.to change(Manual, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post manuals_url, params: { manual: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {marca: :Brastemp, codigo: :abc, modelo: :plus, path: 'www.marca.com'}
      end

      it 'updates the requested manual' do
        manual = Manual.create! valid_attributes
        patch manual_url(manual), params: { manual: new_attributes }
        manual.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the manual' do
        manual = Manual.create! valid_attributes
        patch manual_url(manual), params: { manual: new_attributes }
        manual.reload
        expect(response).to redirect_to(manual_url(manual))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        manual = Manual.create! valid_attributes
        patch manual_url(manual), params: { manual: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end
end
